name: Entrega continua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
    # Artifact name
        name: programa
    - uses: actions/checkout@v3
    
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"

    - name: Create .env file
      run: |
        echo "DBHOST=${{ secrets.DBHOST }}" >> .env
        echo "DBUSER=${{ secrets.DBUSER }}" >> .env
        echo "DBPASSWORD=${{ secrets.DBPASSWORD }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "DBPORT=${{ secrets.DBPORT }}" >> .env
        echo "PORT=8000" >> .env
    
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DBHOST,DBUSER,DBPASSWORD,DBNAME,DBPORT,PORT
        script: |
          nohup env \
            DBHOST=${{ secrets.DBHOST }} \
            DBUSER=${{ secrets.DBUSER }} \
            DBPASSWORD=${{ secrets.DBPASSWORD }} \
            DBNAME=${{ secrets.DBNAME }} \
            DBPORT=${{ secrets.DBPORT }} \
            PORT=8000 \
            ./main > nohup.out 2> nohup.err < /dev/null &

        
        
